### ISSUE TITLE
Issue example:

### ISSUE THREAD

**Issue by alealcor** [lee-fcsh/lilo#1]
* Capacitar a programadores
- [ ] Este es para tachar

Se recomienda crear un nuevo repo para este experimeto y luego instalar ciertas cosas.

```
pip install python
```

**Comment by tati-18** [comment]
Todo bien

**Comment by alealcor** [comment]
@tati-18 @maalloor @Tvillago por favor revisar

**Comment by Tvillago** [comment]
listo

**Comment by maalloor** [comment]
Perfect!

**Comment by alealcor** [comment]
![image](https://user-images.githubusercontent.com/33164007/170844242-d6d86613-bd96-4068-82d4-cc5b0b318a19.png)

**Comment by tati-18** [comment]
no
